### ISSUE TITLE
Quantas presenças

### ISSUE THREAD

**Issue by yuriploc** [tavares1/hellojs-s03e03#1]
@tavares1 se eu rodar o [desafio.js](../blob/master/intro-knex/desafio.js) mais de uma vez, quantas vezes ele vai anotar as presenças? Posso ter um aluno com mais de uma presença em um dia?

**Comment by tavares1** [comment]
Vou fazer um select que verifica se o aluno já está presente no episódio antes de adicionar.

**Comment by tavares1** [comment]
tive um problema com o process.exit dentro do for, pq ele acaba inserindo só a última. Tem alguma dica?

**Comment by tavares1** [comment]
corrigido o insert.
